# Default values for node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  pullPolicy: IfNotPresent
service:
  name: node
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080
  hostPort: 8200
resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 512Mi
ingress:
  enabled: false
